export const INSERT_COMMENT_SAGA = 'INSERT_COMMENT_SAGA';
export const GET_TASK_COMMENT = 'GET_TASK_COMMENT';
export const GET_TASK_COMMENT_SAGA = 'GET_TASK_COMMENT_SAGA';
export const EDIT_COMMENT_SAGA = 'EDIT_COMMENT_SAGA';
export const DELETE_COMMENT_SAGA = 'DELETE_COMMENT_SAGA';

