export const GET_USER_BY_PROJECT_ID_SAGA = 'GET_USER_BY_PROJECT_ID_SAGA';
export const GET_USER_BY_PROJECT_ID = 'GET_USER_BY_PROJECT_ID';
//MANAGER USER
export const GET_ALL_USER_REDUCER = 'GET_ALL_USER_REDUCER'; 
export const GET_ALL_USERS_SAGA = 'GET_ALL_USERS_SAGA';  
export const DELETE_USER_FROM_LIST_SAGA = 'DELETE_USER_FROM_LIST_SAGA'; 
export const EDIT_USER_INFO_SAGA = 'EDIT_USER_INFO_SAGA'
export const USER_SIGN_UP_SAGA = 'USER_SIGN_UP_SAGA';
export const USER_EDIT_INFO_REDUCER = 'USER_EDIT_INFO_REDUCER'; 
export const OPEN_FORM_EDIT_USER_INFO = 'OPEN_FORM_EDIT_USER_INFO'; 
export const OPEN_FORM_CREATE_USER = 'OPEN_FORM_CREATE_USER'
export const CREATE_A_USER = 'CREATE_A_USER'; 
export const USER_SIGNIN_API = "USER_SIGNIN_API"; 
export const USLOGIN = "USLOGIN";
export const DELETE_USER_PROJECT_API = 'DELETE_USER_PROJECT_API';
export const SET_SUBMIT_CREATE_A_USER= 'SET_SUBMIT_CREATE_A_USER';
export const SET_SUBMIT_EDIT_USER_INFO= 'SET_SUBMIT_EDIT_USER_INFO';
